spring.application.name=OpenForms (Development)

spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

server.servlet.encoding.charset=UTF-8
server.tomcat.uri-encoding=UTF-8

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

spring.jackson.default-property-inclusion=non_null

spring.mail.host=
spring.mail.port=
spring.mail.username=
spring.mail.password=

spring.thymeleaf.cache=false
devtools.livereload.enabled = true

server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
server.compression.min-response-size=2048

openforms.http.allowedEndpoint="http://localhost:8080/"
openforms.secret=b3886dba5e6e3385f8c3b64c637d97181e66a9458787a2bc5dba3a78ca6e84c6c6be760ee656bddbe85b5b343527b70cfabc44c2d65325afc0f526e8424d392b
